//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelpDeskCore.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur et/ou mot de passe incorrect ou compte désactivé..
        /// </summary>
        public static string BadLoginAttempt {
            get {
                return ResourceManager.GetString("BadLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas commenter ce ticket..
        /// </summary>
        public static string CannotCommentIssue {
            get {
                return ResourceManager.GetString("CannotCommentIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Facebook invalide..
        /// </summary>
        public static string ExternalAuthInvalidFacebookToken {
            get {
                return ResourceManager.GetString("ExternalAuthInvalidFacebookToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create local user account..
        /// </summary>
        public static string ExternalAuthLocalAccountCreationFailed {
            get {
                return ResourceManager.GetString("ExternalAuthLocalAccountCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôte &apos;{0}&apos; inconnu ou injoignable. Vérifiez que votre machine est bien connectée au réseau (local et/ou internet)..
        /// </summary>
        public static string SmtpHostUnreachable {
            get {
                return ResourceManager.GetString("SmtpHostUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le serveur SMTP ne supporte pas les connexions via SSL/TLS..
        /// </summary>
        public static string SmtpServerDoesNotSupportSsl {
            get {
                return ResourceManager.GetString("SmtpServerDoesNotSupportSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le serveur SMTP exige l&apos;authentification.
        /// </summary>
        public static string SmtpServerRequiresAuth {
            get {
                return ResourceManager.GetString("SmtpServerRequiresAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie &apos;{0}&apos; créée..
        /// </summary>
        public static string SysEventCategoryCreated {
            get {
                return ResourceManager.GetString("SysEventCategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie &apos;{0}&apos; supprimée..
        /// </summary>
        public static string SysEventCategoryDeleted {
            get {
                return ResourceManager.GetString("SysEventCategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie &apos;{0}&apos; mise à jour..
        /// </summary>
        public static string SysEventCategoryUpdated {
            get {
                return ResourceManager.GetString("SysEventCategoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres de la messagerie mis à jour..
        /// </summary>
        public static string SysEventEmailConfigUpdated {
            get {
                return ResourceManager.GetString("SysEventEmailConfigUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;envoyer un e-mail..
        /// </summary>
        public static string SysEventEmailSendFailed {
            get {
                return ResourceManager.GetString("SysEventEmailSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail envoyé avec succès..
        /// </summary>
        public static string SysEventEmailSendSuccess {
            get {
                return ResourceManager.GetString("SysEventEmailSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket #{0} assigné à {1}..
        /// </summary>
        public static string SysEventIssueAssigned {
            get {
                return ResourceManager.GetString("SysEventIssueAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket #{0} fermé par {1}..
        /// </summary>
        public static string SysEventIssueClosed {
            get {
                return ResourceManager.GetString("SysEventIssueClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vient de soumettre un ticket..
        /// </summary>
        public static string SysEventIssueCreated {
            get {
                return ResourceManager.GetString("SysEventIssueCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket #{0} supprimé par {1}..
        /// </summary>
        public static string SysEventIssueDeleted {
            get {
                return ResourceManager.GetString("SysEventIssueDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket #{0} rouvert par {1}..
        /// </summary>
        public static string SysEventIssueReopened {
            get {
                return ResourceManager.GetString("SysEventIssueReopened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket #{0} mis à jour par {1}..
        /// </summary>
        public static string SysEventIssueUpdated {
            get {
                return ResourceManager.GetString("SysEventIssueUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative de connexion au compte &apos;{0}&apos; échouée..
        /// </summary>
        public static string SysEventLoginFailure {
            get {
                return ResourceManager.GetString("SysEventLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vient de se connecter..
        /// </summary>
        public static string SysEventLoginSuccess {
            get {
                return ResourceManager.GetString("SysEventLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vient de se déconnecter..
        /// </summary>
        public static string SysEventLogout {
            get {
                return ResourceManager.GetString("SysEventLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le compte {0} a été créé avec succès..
        /// </summary>
        public static string SysEventUserCreated {
            get {
                return ResourceManager.GetString("SysEventUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le compte &apos;{0}&apos; a été supprimé..
        /// </summary>
        public static string SysEventUserDeleted {
            get {
                return ResourceManager.GetString("SysEventUserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur &apos;{0}&apos; importé..
        /// </summary>
        public static string SysEventUserImported {
            get {
                return ResourceManager.GetString("SysEventUserImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vient de s&apos;enregistrer..
        /// </summary>
        public static string SysEventUserRegistered {
            get {
                return ResourceManager.GetString("SysEventUserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails de &apos;{0}&apos; mis à jour..
        /// </summary>
        public static string SysEventUserUpdated {
            get {
                return ResourceManager.GetString("SysEventUserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau ticket créé.
        /// </summary>
        public static string TicketCreated {
            get {
                return ResourceManager.GetString("TicketCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket non mis à jour.
        /// </summary>
        public static string TicketNotUpdated {
            get {
                return ResourceManager.GetString("TicketNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entreprise.
        /// </summary>
        public static string TicketSortingCompany {
            get {
                return ResourceManager.GetString("TicketSortingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TicketSortingDate {
            get {
                return ResourceManager.GetString("TicketSortingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date butoire.
        /// </summary>
        public static string TicketSortingDeadline {
            get {
                return ResourceManager.GetString("TicketSortingDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        public static string TicketSortingFrom {
            get {
                return ResourceManager.GetString("TicketSortingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de ticket.
        /// </summary>
        public static string TicketSortingId {
            get {
                return ResourceManager.GetString("TicketSortingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière modification.
        /// </summary>
        public static string TicketSortingLastModified {
            get {
                return ResourceManager.GetString("TicketSortingLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorité.
        /// </summary>
        public static string TicketSortingPriority {
            get {
                return ResourceManager.GetString("TicketSortingPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string TicketSortingStatus {
            get {
                return ResourceManager.GetString("TicketSortingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objet.
        /// </summary>
        public static string TicketSortingSubject {
            get {
                return ResourceManager.GetString("TicketSortingSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech.
        /// </summary>
        public static string TicketSortingTech {
            get {
                return ResourceManager.GetString("TicketSortingTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le ticket a été mis à jour.
        /// </summary>
        public static string TicketUpdated {
            get {
                return ResourceManager.GetString("TicketUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue sur Help Desk.
        /// </summary>
        public static string WelcomeOnHelpDesk {
            get {
                return ResourceManager.GetString("WelcomeOnHelpDesk", resourceCulture);
            }
        }
    }
}
